# Generated by Django 3.2.6 on 2021-12-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_product_imagepresent'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailorder',
            name='isRating',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
